---
title: 'BYU Stat 223: Applied R Programming'
output: html_document
---

This is the homepage for BYU Stats 223: Applied R Programming.

---

**Section 002** | MW 3:25 - 4:45 | *2104 JKB*


**Section 004** | MW 4:55 - 6:15 | *2104 JKB*

---

### Instructor
The instructor for this course is James Blair.

* Office: 204 TMCB (On campus Mon and Wed only)
  * Office Hours:
    * Monday 1:00-1:30 pm
    * Wednesday 2:30-3:00 pm
* Email: [blair@stat.byu.edu](mailto:blair@stat.byu.edu)

### TAs
* Adam Ott | [adderotter@hotmail.com](mailto:adderotter@hotmail.com)
  * Office Hours (235 TMCB)
    - Monday 9:00-11:00 am
    - Wednesday 9:00-11:00 am
    
* Dallin Biorn | [biorndallin@gmail.com](mailto:biorndallin@gmail.com)
  * Office Hours (235 TMCB)
      - Monday 12:30-1:30 pm
      - Tuesday 12:00-1:00 pm
      - Wednesday 12:30-1:30 pm

* Jungeol Kim | [ldskimjg@gmail.com](mailto:ldskimjg@gmail.com)
  * Office Hours (235 TMCB)
    - Monday 9:30-11:50 am
    - Wednesday 9:30-11:50 am
    - Friday 9:00-10:00 am; 10:30-11:50 am
    
* Matthew Morgan | [matt4byu@gmail.com](mailto:matt4byu@gmail.com)
  * Office Hours (235 TMCB)
    - Monday 8:00-8:50 am
    - Tuesday 8:00-9:00 am
    - Wednesday 8:00-8:50 am
    - Thursday 8:00-9:00 am
    - Friday 8:00-8:50 am